#!/usr/bin/env perl
use Mojolicious::Lite;

use Mojo::JSON;
use Mojo::Util 'dumper';
use Mojo::File 'path';

plugin 'Config';
plugin 'OAuth2' => app->config('oauth2');

get '/' => 'index';

get "/connect" => sub {
  my $c = shift;
  warn "In connect";
  $c->delay(
    sub {
      my $delay = shift;
      my $args = {redirect_uri => $c->url_for('connect')->userinfo(undef)->to_abs};
      warn "getting token";
      $c->oauth2->get_token(hubspot => $args, $delay->begin);
    },
    sub {
      my ($delay, $err, $data) = @_;
      warn "Now what???";
      $c->app->log->error(dumper $err);
      $c->app->log->info(dumper $data);
      return $c->render("connect", error => $err) unless $data->{access_token};
      # Store the token somewhere
      path('token')->spurt($data->{access_token});
      $c->app->log->debug($data->{access_token});
      return $c->redirect_to('index');
    },
  );
};

# Mojo::IOLoop->recurring(20000 => sub { refresh_token });

app->start;

__DATA__

@@ index.html.ep
% layout 'default';
% title 'Welcome';
%= $c->oauth2->auth_url("hubspot", scope => "automation business-intelligence contacts content e-commerce files hubdb integration-sync reports social tickets transactional-email", redirect_uri => $c->url_for('connect')->userinfo(undef)->to_abs)
<br>
<%= link_to "Connect to Hubspot!", $c->oauth2->auth_url("hubspot", scope => "automation business-intelligence contacts content e-commerce files hubdb integration-sync reports social tickets transactional-email", redirect_uri => $c->url_for('connect')->userinfo(undef)->to_abs) %>
forms
timeline

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body><%= content %></body>
</html>
